app:
  port: 3000
  timeout: 60
db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db_name: users
  ssl_mode: disable
  timeout: 20
redis:
  host: redis
  port: 6379
  db: 0
token:
  access:
    token_secret: superdupersecret
    ttl: 900
  refresh:
    token_secret: superdupersecretofsecrets
    ttl: 9000
